export const ALCHEMY_API_KEY = process.env.REACT_APP_ALCHEMY_API_KEY ?? ''
export const PROJECT_ID = process.env.REACT_APP_PROJECT_ID ?? ''
export const DEVNET_PRIVKEY = process.env.REACT_APP_DEVNET_PRIVKEY ?? ''
export const L2RPC = process.env.REACT_APP_L2RPC ?? ''
export const L1RPC = process.env.REACT_APP_L1RPC ?? ''
